/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module iiitb_mux(out, a, b, c, d, s0, s1);
  input a;
  input b;
  input c;
  input d;
  output out;
  input s0;
  input s1;
  sky130_fd_sc_hd__mux4_2 _0_ (
    .A0(a),
    .A1(b),
    .A2(c),
    .A3(d),
    .S0(s1),
    .S1(s0),
    .X(out)
  );
endmodule
